<?php
/**
 * Initializes the settings extension for this module.
 */

declare( strict_types = 1 );

namespace WooCommerce\PayPalCommerce\AgenticCommerce\Setting;

use WooCommerce\PayPalCommerce\Settings\Endpoint\ExtensionRestEndpoint;

class AgenticSettingsModule {

	private const ASSETS_DIR = 'modules/ppcp-agentic-commerce/assets/';
	private string $absolute_plugin_path;
	private string $plugin_main_file;
	private ExtensionRestEndpoint $settings_endpoint;

	public function __construct(
		string $absolute_plugin_path,
		string $plugin_main_file,
		ExtensionRestEndpoint $settings_endpoint
	) {

		$this->absolute_plugin_path = $absolute_plugin_path;
		$this->plugin_main_file     = $plugin_main_file;
		$this->settings_endpoint    = $settings_endpoint;
	}

	public function init(): void {
		// Enqueue the JS module with the custom settings component.
		add_action(
			'woocommerce_paypal_payments_settings_scripts_enqueued',
			fn() => $this->enqueue_settings_script()
		);

		// Register the settings REST endpoint.
		add_action(
			'rest_api_init',
			fn() => $this->settings_endpoint->register_routes()
		);
	}

	private function enqueue_settings_script(): void {
		$assets_path = $this->absolute_plugin_path . self::ASSETS_DIR;
		$assets_url  = plugins_url( self::ASSETS_DIR, $this->plugin_main_file );

		/** @psalm-suppress UnresolvableInclude - this file is generated by webpack and must be present */
		$script_asset_file = require $assets_path . '/settings.asset.php';

		wp_enqueue_script(
			'ppcp-agentic-commerce-settings',
			$assets_url . '/settings.js',
			$script_asset_file['dependencies'],
			$script_asset_file['version'],
			true
		);
	}
}
