[files]
extend-exclude = [
	".git/",
	".ddev/bin/",
	"modules/ppcp-order-tracking/carriers.php",
	"stubs/",
	"tests/",
	# German
	"modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php",
	# Files outside the repository
	"node_modules/",
	"vendor/",
	"*.min.js",
	"*.min.css",
]
ignore-hidden = false

[default]
extend-ignore-re = [
	"\\bBig Sur\\b",
	"[0-9A-Za-z/+]{64}",
	"'PN',",
	"'AU' => '[^']+'",
	"define\\( 'CONNECT_WOO_SANDBOX_CLIENT_ID', '[^']+'",
	# German
	"Unter den .*",
	"Die Kombination .*",
	"Die gewählte .*",
	# Lorem ipsum
	"Lorem ipsum .*",
	"Id cursus metus .*",
	"Urna et pharetra .*",
	"Mattis nunc sed .*",
	"Vestibulum lectus .*",
]

[default.extend-words]
ba = "ba"

[default.extend-identifiers]
Automattic = "Automattic"
automattic = "automattic"
PayPal = "PayPal"
paypal = "paypal"
# Typos
Github = "GitHub"
Wordpress = "WordPress"
Woocommerce = "WooCommerce"
Fatslane = "Fastlane"
Fastalne = "Fastlane"
Faslane = "Fastlane"
Fastlain = "Fastlane"
Fasltane = "Fastlane"
Fastlan = "Fastlane"
Fastlanne = "Fastlane"
Fatstlane = "Fastlane"
Fstlane = "Fastlane"
