#!/bin/bash

## Reset the WordPress database and install WordPress with the desired settings

wp db reset --yes && \
wp core install \
  --url=wp-test-site.ddev.site \
  --title="Testing Cart" \
  --admin_user=admin \
  --admin_password=password \
  --admin_email=test@ddev.site
