#!/bin/bash

help-panel() {
	echo -e "-p [post type] Delete all posts"
	echo -e "\tExample: -p shop_order,product"
	echo -e "-l [wp-content path] Delete all logs"
	echo -e "\tExample: -l uploads/wc-logs"
}

delete-posts() {
	for post in $(wp post list --post_type=$1 --format=ids --path=.ddev/wordpress); do
		wp post delete $post --force --path=.ddev/wordpress
	done
}

delete-logs() {
	rm .ddev/wordpress/wp-content/$1/*.log
}

declare -i param_counter=0

while getopts "d:l:h" arg; do
	case $arg in
	d) delete-posts $OPTARG; param_counter+=1 ;;
	l) delete-logs $OPTARG; param_counter+=1 ;;
	h) help-panel ;;
	esac
done

if [ $param_counter -eq 0 ]; then
	help-panel
fi
