name: Integration tests

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
        wc-versions: ['9.7.1']

    name: PHP ${{ matrix.php-versions }} WC ${{ matrix.wc-versions }}
    steps:
    - uses: ddev/github-action-setup-ddev@1c7ef18595da42355373cb6d9417a6f44d758b93 # v1.10.1
      with:
        autostart: false

    - uses: actions/checkout@v1

    - name: Configure DDEV PHP
      run: ddev config --php-version ${{ matrix.php-versions }}
    - name: Configure DDEV WC
      run: ddev config --web-environment-add="WC_VERSION=${{ matrix.wc-versions }}"

    - name: Start DDEV
      run: ddev start

    - name: Orchestrate DDEV
      run: ddev orchestrate -f

    - name: Create config
      run: cp -n .env.integration.example .env.integration

    - name: Setup tests
      run: ddev php tests/integration/PHPUnit/setup.php

    - name: Run PHPUnit
      run: ddev exec phpunit --exclude skip-ci -c tests/integration/phpunit.xml.dist
