name: CI

on: [push]

jobs:
  coding-standards-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PHP_VERSION: '8.0'
      PHPCS_ARGS: '--report-full --runtime-set ignore_warnings_on_exit 1'
  static-code-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
    with:
      PHP_VERSION: '8.0'
      PHPSTAN_ARGS: '--no-progress --memory-limit=2G'
  tests-unit-php:
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    with:
      PHPUNIT_ARGS: ''
      PHP_VERSION: ${{ matrix.php }}
