name: PR Playground Demo

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
permissions: {}

jobs:
  fetch_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository == 'woocommerce/woocommerce-paypal-payments'
    permissions:
      actions: read
    outputs:
      artifact_name: ${{ steps.version.outputs.artifact_name }}
      plugin_version: ${{ steps.version.outputs.plugin_version }}
      has_build: ${{ steps.fetch.outputs.has_build }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set plugin version and artifact name
        id: version
        run: |
          BASE_VERSION=$(sed -nE '/Version:/s/.* ([0-9.]+).*/\1/p' woocommerce-paypal-payments.php)
          VERSUFFIX="${GITHUB_RUN_ID}-g$(git rev-parse --short HEAD)"
          PR_VERSION="${BASE_VERSION}-pr${{ github.event.pull_request.number }}-${VERSUFFIX}"
          ARTIFACT_NAME="woocommerce-paypal-payments-${PR_VERSION}"
          echo "plugin_version=$PR_VERSION" >> $GITHUB_OUTPUT
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: Wait for and download Build and distribute artifact
        id: fetch
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            const script = require('./.github/scripts/fetch-build-artifact.js');
            await script.run({ github, context, core, zipPath: '/tmp/plugin.zip' });

      - name: Unzip artifact
        if: steps.fetch.outputs.has_build == 'true'
        run: |
          mkdir -p /tmp/plugin-build
          unzip -o /tmp/plugin.zip -d /tmp/plugin-build

      - name: Re-upload artifact for Playground
        if: steps.fetch.outputs.has_build == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.version.outputs.artifact_name }}
          path: /tmp/plugin-build

  playground_demo:
    name: Comment on PR with Playground details
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: fetch_build
    if: needs.fetch_build.outputs.has_build == 'true'
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Create or update PR playground comment
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            const script = require('./.github/scripts/playground-comment.js');

            process.env.PLUGIN_VERSION = '${{ needs.fetch_build.outputs.plugin_version }}';
            process.env.ARTIFACT_NAME = '${{ needs.fetch_build.outputs.artifact_name }}';

            await script.run({ github, context, core });
