name: 'Weekly builds'
on:
  schedule:
    - cron:  '0 11 * * 2' # Run every Tuesday at 11 AM UTC (12pm CET)
  workflow_dispatch:

env:
  SOURCE_REF: develop

jobs:
  create-tag:
    if: github.repository_owner == 'woocommerce'
    name: Create weekly tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      weekly_tag: ${{ steps.create_release.outputs.weekly_tag }}
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create weekly tag and release
        id: create_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sourceRef = process.env.SOURCE_REF;

            const latestRelease = await github.rest.repos.getLatestRelease({
              ...context.repo
            });
            const latestTag = latestRelease.data.tag_name;

            // Generate tag name
            const now = new Date();
            const month = String(now.getMonth() + 1).padStart(2, '0');
            const day = String(now.getDate()).padStart(2, '0');
            const year = String(now.getFullYear());
            const weeklyTag = `${latestTag}-alpha${year}${month}${day}`;

            const branchData = await github.rest.repos.getBranch({
              ...context.repo,
              branch: sourceRef,
            });

            await github.rest.git.createRef({
              ...context.repo,
              ref: `refs/tags/${weeklyTag}`,
              sha: branchData.data.commit.sha,
            });

            // Create a new release
            const release = await github.rest.repos.createRelease({
              ...context.repo,
              tag_name: weeklyTag,
              name: `Weekly Build ${year}-${month}-${day}`,
              body: `Weekly build Autogenerated every Tuesday at 12pm CET`,
              draft: false,
              prerelease: true,
            });

            core.setOutput('weekly_tag', weeklyTag);
            core.setOutput('upload_url', release.data.upload_url);

  build:
    if: github.repository_owner == 'woocommerce'
    name: Build package
    needs: create-tag
    uses: inpsyde/reusable-workflows/.github/workflows/build-plugin-archive.yml@a9af34f34e95cbe18703198c7e972e97ebcd7473
    with:
      PHP_VERSION: 7.4
      NODE_VERSION: 22
      PLUGIN_MAIN_FILE: ./woocommerce-paypal-payments.php
      PLUGIN_VERSION: ${{ needs.create-tag.outputs.weekly_tag }}
      PLUGIN_FOLDER_NAME: woocommerce-paypal-payments
      ARCHIVE_NAME: woocommerce-paypal-payments
      COMPILE_ASSETS_ARGS: '-vv --env=root'

  deploy:
    if: github.repository_owner == 'woocommerce'
    name: Upload weekly build
    runs-on: ubuntu-latest
    needs: [create-tag, build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: woocommerce-paypal-payments
          path: ./artifacts

      - name: Create and upload zip file
        working-directory: ./artifacts
        run: |
          zip -r ./woocommerce-paypal-payments-weekly.zip ./woocommerce-paypal-payments

      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-tag.outputs.release_upload_url }}
          asset_path: ./artifacts/woocommerce-paypal-payments-weekly.zip
          asset_name: woocommerce-paypal-payments-weekly.zip
          asset_content_type: application/zip

  notify-slack:
    if: always() && github.repository_owner == 'woocommerce'
    name: Send Slack notification
    runs-on: ubuntu-latest
    needs: [ create-tag, build, deploy ]
    steps:
      - name: Send success message to Slack
        if: needs.deploy.result == 'success'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.WEEKLY_RELEASE_SLACK_HOOK }}
          webhook-type: webhook-trigger
          payload: |
            "status": "🎉 A new Weekly Pre Release has been uploaded",
            "workflow": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send failure message to Slack
        if: needs.deploy.result == 'failure' || needs.build.result == 'failure' || needs.create-tag.result == 'failure'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.WEEKLY_RELEASE_SLACK_HOOK }}
          webhook-type: webhook-trigger
          payload: |
            "status": "😰 Ups! It was an error uploading the Weekly Pre Release",
            "workflow": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
